apiVersion: v1
kind: Namespace
metadata:
    name: warehouse-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: warehouse
    namespace: warehouse-system

spec:
    selector:
        matchLabels:
            app: warehouse

    template:
        metadata:
            labels:
                app: warehouse

        spec:
            terminationGracePeriodSeconds: 60

            initContainers:
                - name: init-migrate-seed
                  image: warehouse-image
                  command: ["./admin", "migrate-seed"]
                  env:
                      - name: WAREHOUSE_DB_USER
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_user
                                optional: true
                      - name: WAREHOUSE_DB_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_password
                                optional: true
                      - name: WAREHOUSE_DB_HOST_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_hostport
                                optional: true
                      - name: WAREHOUSE_DB_DISABLE_TLS
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_disabletls
                                optional: true

            containers:
                - name: warehouse
                  image: warehouse-image

                  ports:
                      - name: warehouse
                        containerPort: 3000
                      - name: warehouse-debug
                        containerPort: 3010

                  readinessProbe: # readiness probes mark the service available to accept traffic.
                      httpGet:
                          path: /v1/readiness
                          port: 3000
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                      successThreshold: 1
                      failureThreshold: 2

                  livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
                      httpGet:
                          path: /v1/liveness
                          port: 3000
                      initialDelaySeconds: 2
                      periodSeconds: 5
                      timeoutSeconds: 5
                      successThreshold: 1
                      failureThreshold: 2

                  env:
                      - name: GOMAXPROCS
                        valueFrom:
                            resourceFieldRef:
                                resource: limits.cpu

                      - name: GOGC
                        value: "off"

                      - name: GOMEMLIMIT
                        valueFrom:
                            resourceFieldRef:
                                resource: limits.memory

                      - name: WAREHOUSE_DB_USER # here as an example for configuring a hosted db.
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_user
                                optional: true
                      - name: WAREHOUSE_DB_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_password
                                optional: true
                      - name: WAREHOUSE_DB_HOST_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_hostport
                                optional: true
                      - name: WAREHOUSE_DB_DISABLE_TLS
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: db_disabletls
                                optional: true

                      - name: KUBERNETES_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                      - name: KUBERNETES_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: KUBERNETES_POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: KUBERNETES_NODE_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: spec.nodeName

                - name: metrics
                  image: metrics-image

                  ports:
                      - name: metrics
                        containerPort: 4000
                      - name: metrics-debug
                        containerPort: 4010
                      - name: metrics-prom
                        containerPort: 4020

                  env:
                      - name: GOMAXPROCS
                        valueFrom:
                            resourceFieldRef:
                                resource: limits.cpu

---
apiVersion: v1
kind: Service
metadata:
    name: warehouse-service
    namespace: warehouse-system

spec:
    selector:
        app: warehouse
