apiVersion: v1
kind: Service
metadata:
    name: warehouse-service
    namespace: warehouse-system

spec:
    type: ClusterIP

    ports:
        - name: warehouse
          port: 3000
          targetPort: warehouse
        - name: warehouse-debug
          port: 3010
          targetPort: warehouse-debug
        - name: metrics
          port: 4000
          targetPort: metrics
        - name: metrics-debug
          port: 4010
          targetPort: metrics-debug
    # - name: prometheus
    #   port: 4020
    #   targetPort: metrics-prom
