apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../base/warehouse/
    - ./dev-warehouse-configmap.yaml
patches:
    - path: ./dev-warehouse-patch-deploy.yaml
    - path: ./dev-warehouse-patch-service.yaml
images:
    - name: warehouse-image
      newName: localhost/medisync/warehouse
      newTag: 0.0.1
    - name: metrics-image
      newName: localhost/medisync/metrics
      newTag: 0.0.1
